export const GET_MSGLIST_SUCCESS = 'GET_MSGLIST_SUCCESS';
export type GET_MSGLIST_SUCCESS = typeof GET_MSGLIST_SUCCESS;

export const REC_MSG_SUCCESS = 'REC_MSG_SUCCESS';
export type REC_MSG_SUCCESS = typeof REC_MSG_SUCCESS;

export const UPDATE_MSG_SUCCESS = 'UPDATE_MSG_SUCCESS';
export type UPDATE_MSG_SUCCESS = typeof UPDATE_MSG_SUCCESS;
