export const SELECT_JOB = 'SELECT_JOB';
export type SELECT_JOB = typeof SELECT_JOB;

export const SELECT_CITY = 'SELECT_CITY';
export type SELECT_CITY = typeof SELECT_CITY;

export const SELECT_SALARY = 'SELECT_SALARY';
export type SELECT_SALARY = typeof SELECT_SALARY;

export const SELECT_SENIORITY = 'SELECT_SENIORITY';
export type SELECT_SENIORITY = typeof SELECT_SENIORITY;

export const LOAD_USERLIST_SUCCESS = 'LOAD_USERLIST_SUCCESS';
export type LOAD_USERLIST_SUCCESS = typeof LOAD_USERLIST_SUCCESS;

export const REFRESH_USERLIST_SUCCESS = 'REFRESH_USERLIST_SUCCESS';
export type REFRESH_USERLIST_SUCCESS = typeof REFRESH_USERLIST_SUCCESS;
